version: 2 # use CircleCI 2.1 - Enabled preview

jobs:
    build:
        docker: # run the steps with Docker
            - image: circleci/openjdk:8-jdk # ...with this image as the primary container; this is where all `steps` will run
        working_directory: ~/repo
        environment:
          # Customize the JVM maximum heap limit
          MAVEN_OPTS: -Xmx3200m
        steps:
            - checkout
            - restore_cache:
                keys:
                  - v1-dependencies-{{ checksum "pom.xml" }}
                  # fallback to using the latest cache if no exact match is found
                  - v1-dependencies-

            - run: mvn dependency:go-offline # gets the project dependencies

            - save_cache:
                paths:
                  - ~/.m2
                key: v1-dependencies-{{ checksum "pom.xml" }}
            - run: openssl version
            - run: gpg --version
            - run: export GPG_TTY=$(tty)
            - run: openssl aes-256-cbc -d -in codesigning.asc.enc -md md5 -out codesigning.asc -k $ENCKEY
            - run: gpg --batch --import codesigning.asc
            - run: mvn deploy -P sign,build-extras --settings settings.xml